'use strict';

const bsn = require('bootstrap.native/dist/bootstrap-native-v4');

import {initAccordionHandlers} from "./bs4/modules/MobileMenu";
import Overlay from './bs4/modules/Overlay';
import SearchForm from './bs4/modules/SearchForm';
import UserNavMenu from "./bem/UserNavMenu";
import OtherCategoriesModal from "./bs4/modules/OtherCategoriesModal";

(new OtherCategoriesModal()).init();
(new Overlay()).init();
(new SearchForm()).init();

// LMS-8483 universal user menu generated by JS to alleviate issues with caching
const userNavMenu = new UserNavMenu();
userNavMenu.setBSN(bsn);
userNavMenu.init(() => {
    initAccordionHandlers();
});
